use_frameworks!

target 'MGSegmented_Example' do
  pod 'MGSegmented', :path => '../'

  target 'MGSegmented_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
